server:
  port: 8805
spring:
  application:
    name: api-pound
  aop:
    auto: true # 启动aop配置
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
