server:
  port: 8700
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://code.aliyun.com/51gkp-api-1/b2b2c-config.git
          search-paths: config-repo
          username: zhangbo_magic
          password: magic1028
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://registry:8800/eureka/

