server:
  debug:
    port: 87611
  port: 8800
debug:
  opts: -Xdebug -Xnoagent -Xrunjdwp:transport=dt_socket,server=y,address=${server.debug.port},suspend=n
eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://registry:8800/eureka/
  server:
    eviction-interval-timer-in-ms: 3000
